"""drop flag unique constraint

Revision ID: b718517c9536
Revises: aa88f392562b
Create Date: 2026-07-20 17:28:19.743111
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b718517c9536'
down_revision: Union[str, None] = 'aa88f392562b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flag_run_id_type_project_id_person_id_key', 'flag', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('flag_run_id_type_project_id_person_id_key', 'flag', ['run_id', 'type', 'project_id', 'person_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
